[package]
name = "jade_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
itertools = "0.15.0"
jade_core = { version = "0.1.0", path = "../jade_core" }
jade_nav = { version = "0.1.0", path = "../jade_nav" }
jade_pattern = { version = "0.1.0", path = "../jade_pattern" }
jade_solve = { version = "0.1.0", path = "../jade_solve" }

[lints]
workspace = true
