[package]
name = "jade_solve"
version = "0.1.0"
edition = "2024"

[dependencies]
fumen = "0.1.2"
jade_core = { version = "0.1.0", path = "../jade_core" }
jade_nav = { version = "0.1.0", path = "../jade_nav" }
jade_pattern = { version = "0.1.0", path = "../jade_pattern" }
rayon = "1.12.0"
rustc-hash = "2"

[lints]
workspace = true

[features]
stats = []
